### ISSUE TITLE
Update to 17.0.0

### ISSUE THREAD

**Issue by BSzili** [dandar3/android-google-play-services-safetynet#1]
The current version of safetynet is at:
https://maven.google.com/com/google/android/gms/play-services-safetynet/17.0.0/play-services-safetynet-17.0.0.aar
Could you update this library to the latest version?

**Comment by dandar3** [comment]
Hi @BSzili 

Version 17.0.0 now available, please let me know if any problems.
https://github.com/dandar3/android-google-play-services-safetynet/tree/17.0.0

If you haven't imported any of these libraries before please see the how-to links at the end of the main page.
https://github.com/dandar3/android-google-play-services-README

**Comment by BSzili** [comment]
Thank you, it looks good to me!
